### ISSUE TITLE
DialogExpressionCondition: value is null

### ISSUE THREAD

**Issue by cmucha** [DocuWare/PlatformJavaClient#10]
try to set DialogExpressionCondition:
DialogExpressionCondition debitornamecondition = new DialogExpressionCondition();
debitornamecondition.setDBName("DEBITORNAME");
ArrayList<String> arrayList=new ArrayList<>();
arrayList.add("IT2U GmbH"); 
debitornamecondition.setValue(arrayList);

The queryresult has only one result. The document where field "DEBITORNAME" is empty (=NULL) (there is only one document of 86 where "DEBITORNAME" is null)
It has the same result when i do: debitornamecondition.setValue(null);

**Comment by cmucha** [comment]
close that issue please
I used DialogExpressionCondition.setValue(arrayList) before.
Now I tried DialogExpressionCondition.getValue().add("someString"). That was working....

**Comment by GranatenUdo** [comment]
thanks for reporting back!
