### ISSUE TITLE
Fields of type date are null

### ISSUE THREAD

**Issue by bouil** [DocuWare/PlatformJavaClient#3]
I have a date field for my documents.
The field is not set in the result (in com.docuware.dev.schema._public.services.platform.DocumentsQueryResult -> com.docuware.dev.schema._public.services.platform.Document -> fields -> getItem("MY_DATE_FIELD'")

**Comment by bouil** [comment]
In the XML returned, the date is present 

                <Field FieldName="DATE_DOCUMENT" FieldLabel="Date document">
                    <Date>2015-07-17</Date>
                </Field>

**Comment by GranatenUdo** [comment]
can you tell me whether there is an exception thrown?

**Comment by bouil** [comment]
No exception thrown
