### ISSUE TITLE
PlatformClient log is too verbose about config file missing

### ISSUE THREAD

**Issue by bouil** [DocuWare/PlatformJavaClient#4]
src/com/docuware/dev/Extensions/ PlatformClient line 96 and 125 is very verbose if the src/com/docuware/dev/Extensions/config.properties file is missing.

Of course in case of a deployment, this file will not be here.

1. Default value should be set without warning. I suggest a simple warning log saying that no custom config file is found and that default values will be applied.

2. Any override should be searched in the classpath (using getClass().getResource ) so that an override config file can be loaded in the depending application and not somewhere in the running directory.

**Comment by GranatenUdo** [comment]
I agree, how about #6 ?
